# Generated by Django 5.0.3 on 2024-03-27 11:28

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="작성일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일시"),
                ),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=20, verbose_name="제목")),
                ("content", models.TextField(verbose_name="내용")),
                ("writer", models.CharField(max_length=10, verbose_name="작성자")),
                (
                    "category",
                    models.CharField(
                        choices=[("DIARY", "일기"), ("STUDY", "공부"), ("ETC", "기타")],
                        max_length=10,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="", max_length=30)),
                ("age", models.IntegerField(default=0)),
                ("major", models.CharField(default="", max_length=100)),
                ("github", models.CharField(default="", max_length=200)),
            ],
        ),
    ]
