# Generated by Django 5.0.3 on 2024-04-01 11:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0002_comment"),
    ]

    operations = [
        migrations.CreateModel(
            name="Hashtag",
            fields=[
                ("tag_no", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=30, verbose_name="태그명")),
            ],
        ),
        migrations.AddField(
            model_name="post",
            name="hashtag",
            field=models.ManyToManyField(blank=True, null=True, to="posts.hashtag"),
        ),
    ]
