# Generated by Django 5.0.3 on 2024-04-01 12:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0002_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="writer",
            field=models.IntegerField(verbose_name="작성자"),
        ),
        migrations.AlterField(
            model_name="post",
            name="writer",
            field=models.IntegerField(verbose_name="작성자"),
        ),
    ]
