# Generated by Django 5.0.3 on 2024-04-01 12:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0003_hashtag_post_hashtag"),
        ("posts", "0004_alter_comment_post_id"),
    ]

    operations = []
